package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPing(t *testing.T) {
	request, err := http.NewRequest("GET", "/", nil)
	assert.NoError(t, err)

	response := httptest.NewRecorder()

	// call the ping handler func
	ping(response, request)

	//get the http.Response generated by the ping handler
	result := response.Result()

	// assert that the status code from the ping handler is 200
	assert.Equal(t, http.StatusOK, result.StatusCode)
	//assert that the response body from the ping handler is "OK"
	defer result.Body.Close()
	body, err := io.ReadAll(result.Body)
	assert.NoError(t, err)
	assert.Equal(t, "OK", string(body))

}
